#!/bin/bash

dd bs=1024k skip=$2 count=$3 if=$1 of=$4.raw
convert -size 1820x525 -depth 8 gray:$4.raw $4-raw.png

./ld-decoder.py $4.raw > $4.ld
convert -size 1820x525 -depth 16 gray:$4.ld $4-ld.png

./ntsc -i $4.ld > $4.tbc 
convert -size 844x505 -depth 16 gray:$4.tbc $4-tbc.png

cat $4.tbc | ./comb -d 2 - > $4-2d.rgb
convert -size 744x480 -depth 16 rgb:$4-2d.rgb $4-2d.png

cat $4.tbc | ./comb -d 3 - > $4-3d.rgb
convert -size 744x480 -depth 16 rgb:$4-3d.rgb $4-3d.png

