#!/bin/bash

# params: infile outfile (no suffixes) 
rm $2.avi ; cat $1.tbc | ./comb-pal -d 2 - 2> /dev/null | ffmpeg -f s16le -ar 48k -ac 2 -i $1.pcm -f rawvideo -r 25 -pix_fmt rgb48 -s 974x576 -i /dev/stdin -b:v 15000k -aspect 4:3 -vcodec mpeg4 -flags +ilme+ildct $2.avi
