# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sneki/Documents/domesday/ld-decode-cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sneki/Documents/domesday/ld-decode-cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sneki/Documents/domesday/ld-decode-cmake/CMakeFiles /home/sneki/Documents/domesday/ld-decode-cmake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sneki/Documents/domesday/ld-decode-cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ld-ldf-reader

# Build rule for target.
ld-ldf-reader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-ldf-reader
.PHONY : ld-ldf-reader

# fast build rule for target.
ld-ldf-reader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/build
.PHONY : ld-ldf-reader/fast

#=============================================================================
# Target rules for targets named target

# Build rule for target.
target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 target
.PHONY : target

# fast build rule for target.
target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/target.dir/build.make CMakeFiles/target.dir/build
.PHONY : target/fast

#=============================================================================
# Target rules for targets named ld-ldf-reader_autogen

# Build rule for target.
ld-ldf-reader_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-ldf-reader_autogen
.PHONY : ld-ldf-reader_autogen

# fast build rule for target.
ld-ldf-reader_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader_autogen.dir/build.make CMakeFiles/ld-ldf-reader_autogen.dir/build
.PHONY : ld-ldf-reader_autogen/fast

#=============================================================================
# Target rules for targets named ld-library

# Build rule for target.
ld-library: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-library
.PHONY : ld-library

# fast build rule for target.
ld-library/fast:
	$(MAKE) $(MAKESILENT) -f tools/library/CMakeFiles/ld-library.dir/build.make tools/library/CMakeFiles/ld-library.dir/build
.PHONY : ld-library/fast

#=============================================================================
# Target rules for targets named ld-library_autogen

# Build rule for target.
ld-library_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-library_autogen
.PHONY : ld-library_autogen

# fast build rule for target.
ld-library_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/library/CMakeFiles/ld-library_autogen.dir/build.make tools/library/CMakeFiles/ld-library_autogen.dir/build
.PHONY : ld-library_autogen/fast

#=============================================================================
# Target rules for targets named ld-chroma-decoder

# Build rule for target.
ld-chroma-decoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-decoder
.PHONY : ld-chroma-decoder

# fast build rule for target.
ld-chroma-decoder/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/CMakeFiles/ld-chroma-decoder.dir/build.make tools/ld-chroma-decoder/CMakeFiles/ld-chroma-decoder.dir/build
.PHONY : ld-chroma-decoder/fast

#=============================================================================
# Target rules for targets named ld-chroma-lib

# Build rule for target.
ld-chroma-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-lib
.PHONY : ld-chroma-lib

# fast build rule for target.
ld-chroma-lib/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/CMakeFiles/ld-chroma-lib.dir/build.make tools/ld-chroma-decoder/CMakeFiles/ld-chroma-lib.dir/build
.PHONY : ld-chroma-lib/fast

#=============================================================================
# Target rules for targets named ld-chroma-decoder_autogen

# Build rule for target.
ld-chroma-decoder_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-decoder_autogen
.PHONY : ld-chroma-decoder_autogen

# fast build rule for target.
ld-chroma-decoder_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/CMakeFiles/ld-chroma-decoder_autogen.dir/build.make tools/ld-chroma-decoder/CMakeFiles/ld-chroma-decoder_autogen.dir/build
.PHONY : ld-chroma-decoder_autogen/fast

#=============================================================================
# Target rules for targets named ld-chroma-lib_autogen

# Build rule for target.
ld-chroma-lib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-lib_autogen
.PHONY : ld-chroma-lib_autogen

# fast build rule for target.
ld-chroma-lib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/CMakeFiles/ld-chroma-lib_autogen.dir/build.make tools/ld-chroma-decoder/CMakeFiles/ld-chroma-lib_autogen.dir/build
.PHONY : ld-chroma-lib_autogen/fast

#=============================================================================
# Target rules for targets named ld-chroma-encoder

# Build rule for target.
ld-chroma-encoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-encoder
.PHONY : ld-chroma-encoder

# fast build rule for target.
ld-chroma-encoder/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/encoder/CMakeFiles/ld-chroma-encoder.dir/build.make tools/ld-chroma-decoder/encoder/CMakeFiles/ld-chroma-encoder.dir/build
.PHONY : ld-chroma-encoder/fast

#=============================================================================
# Target rules for targets named ld-chroma-encoder_autogen

# Build rule for target.
ld-chroma-encoder_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-chroma-encoder_autogen
.PHONY : ld-chroma-encoder_autogen

# fast build rule for target.
ld-chroma-encoder_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-chroma-decoder/encoder/CMakeFiles/ld-chroma-encoder_autogen.dir/build.make tools/ld-chroma-decoder/encoder/CMakeFiles/ld-chroma-encoder_autogen.dir/build
.PHONY : ld-chroma-encoder_autogen/fast

#=============================================================================
# Target rules for targets named ld-disc-stacker

# Build rule for target.
ld-disc-stacker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-disc-stacker
.PHONY : ld-disc-stacker

# fast build rule for target.
ld-disc-stacker/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-disc-stacker/CMakeFiles/ld-disc-stacker.dir/build.make tools/ld-disc-stacker/CMakeFiles/ld-disc-stacker.dir/build
.PHONY : ld-disc-stacker/fast

#=============================================================================
# Target rules for targets named ld-disc-stacker_autogen

# Build rule for target.
ld-disc-stacker_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-disc-stacker_autogen
.PHONY : ld-disc-stacker_autogen

# fast build rule for target.
ld-disc-stacker_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-disc-stacker/CMakeFiles/ld-disc-stacker_autogen.dir/build.make tools/ld-disc-stacker/CMakeFiles/ld-disc-stacker_autogen.dir/build
.PHONY : ld-disc-stacker_autogen/fast

#=============================================================================
# Target rules for targets named ld-discmap

# Build rule for target.
ld-discmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-discmap
.PHONY : ld-discmap

# fast build rule for target.
ld-discmap/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-discmap/CMakeFiles/ld-discmap.dir/build.make tools/ld-discmap/CMakeFiles/ld-discmap.dir/build
.PHONY : ld-discmap/fast

#=============================================================================
# Target rules for targets named ld-discmap_autogen

# Build rule for target.
ld-discmap_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-discmap_autogen
.PHONY : ld-discmap_autogen

# fast build rule for target.
ld-discmap_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-discmap/CMakeFiles/ld-discmap_autogen.dir/build.make tools/ld-discmap/CMakeFiles/ld-discmap_autogen.dir/build
.PHONY : ld-discmap_autogen/fast

#=============================================================================
# Target rules for targets named ld-dropout-correct

# Build rule for target.
ld-dropout-correct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-dropout-correct
.PHONY : ld-dropout-correct

# fast build rule for target.
ld-dropout-correct/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-dropout-correct/CMakeFiles/ld-dropout-correct.dir/build.make tools/ld-dropout-correct/CMakeFiles/ld-dropout-correct.dir/build
.PHONY : ld-dropout-correct/fast

#=============================================================================
# Target rules for targets named ld-dropout-correct_autogen

# Build rule for target.
ld-dropout-correct_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-dropout-correct_autogen
.PHONY : ld-dropout-correct_autogen

# fast build rule for target.
ld-dropout-correct_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-dropout-correct/CMakeFiles/ld-dropout-correct_autogen.dir/build.make tools/ld-dropout-correct/CMakeFiles/ld-dropout-correct_autogen.dir/build
.PHONY : ld-dropout-correct_autogen/fast

#=============================================================================
# Target rules for targets named ld-export-metadata

# Build rule for target.
ld-export-metadata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-export-metadata
.PHONY : ld-export-metadata

# fast build rule for target.
ld-export-metadata/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-export-metadata/CMakeFiles/ld-export-metadata.dir/build.make tools/ld-export-metadata/CMakeFiles/ld-export-metadata.dir/build
.PHONY : ld-export-metadata/fast

#=============================================================================
# Target rules for targets named ld-export-metadata_autogen

# Build rule for target.
ld-export-metadata_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-export-metadata_autogen
.PHONY : ld-export-metadata_autogen

# fast build rule for target.
ld-export-metadata_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-export-metadata/CMakeFiles/ld-export-metadata_autogen.dir/build.make tools/ld-export-metadata/CMakeFiles/ld-export-metadata_autogen.dir/build
.PHONY : ld-export-metadata_autogen/fast

#=============================================================================
# Target rules for targets named ld-lds-converter

# Build rule for target.
ld-lds-converter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-lds-converter
.PHONY : ld-lds-converter

# fast build rule for target.
ld-lds-converter/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-lds-converter/CMakeFiles/ld-lds-converter.dir/build.make tools/ld-lds-converter/CMakeFiles/ld-lds-converter.dir/build
.PHONY : ld-lds-converter/fast

#=============================================================================
# Target rules for targets named ld-lds-converter_autogen

# Build rule for target.
ld-lds-converter_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-lds-converter_autogen
.PHONY : ld-lds-converter_autogen

# fast build rule for target.
ld-lds-converter_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-lds-converter/CMakeFiles/ld-lds-converter_autogen.dir/build.make tools/ld-lds-converter/CMakeFiles/ld-lds-converter_autogen.dir/build
.PHONY : ld-lds-converter_autogen/fast

#=============================================================================
# Target rules for targets named ld-process-efm

# Build rule for target.
ld-process-efm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-efm
.PHONY : ld-process-efm

# fast build rule for target.
ld-process-efm/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-efm/CMakeFiles/ld-process-efm.dir/build.make tools/ld-process-efm/CMakeFiles/ld-process-efm.dir/build
.PHONY : ld-process-efm/fast

#=============================================================================
# Target rules for targets named ld-process-efm_autogen

# Build rule for target.
ld-process-efm_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-efm_autogen
.PHONY : ld-process-efm_autogen

# fast build rule for target.
ld-process-efm_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-efm/CMakeFiles/ld-process-efm_autogen.dir/build.make tools/ld-process-efm/CMakeFiles/ld-process-efm_autogen.dir/build
.PHONY : ld-process-efm_autogen/fast

#=============================================================================
# Target rules for targets named ld-process-vbi

# Build rule for target.
ld-process-vbi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-vbi
.PHONY : ld-process-vbi

# fast build rule for target.
ld-process-vbi/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-vbi/CMakeFiles/ld-process-vbi.dir/build.make tools/ld-process-vbi/CMakeFiles/ld-process-vbi.dir/build
.PHONY : ld-process-vbi/fast

#=============================================================================
# Target rules for targets named ld-process-vbi_autogen

# Build rule for target.
ld-process-vbi_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-vbi_autogen
.PHONY : ld-process-vbi_autogen

# fast build rule for target.
ld-process-vbi_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-vbi/CMakeFiles/ld-process-vbi_autogen.dir/build.make tools/ld-process-vbi/CMakeFiles/ld-process-vbi_autogen.dir/build
.PHONY : ld-process-vbi_autogen/fast

#=============================================================================
# Target rules for targets named ld-process-vits

# Build rule for target.
ld-process-vits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-vits
.PHONY : ld-process-vits

# fast build rule for target.
ld-process-vits/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-vits/CMakeFiles/ld-process-vits.dir/build.make tools/ld-process-vits/CMakeFiles/ld-process-vits.dir/build
.PHONY : ld-process-vits/fast

#=============================================================================
# Target rules for targets named ld-process-vits_autogen

# Build rule for target.
ld-process-vits_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-process-vits_autogen
.PHONY : ld-process-vits_autogen

# fast build rule for target.
ld-process-vits_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-process-vits/CMakeFiles/ld-process-vits_autogen.dir/build.make tools/ld-process-vits/CMakeFiles/ld-process-vits_autogen.dir/build
.PHONY : ld-process-vits_autogen/fast

#=============================================================================
# Target rules for targets named ld-analyse

# Build rule for target.
ld-analyse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-analyse
.PHONY : ld-analyse

# fast build rule for target.
ld-analyse/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-analyse/CMakeFiles/ld-analyse.dir/build.make tools/ld-analyse/CMakeFiles/ld-analyse.dir/build
.PHONY : ld-analyse/fast

#=============================================================================
# Target rules for targets named ld-analyse_autogen

# Build rule for target.
ld-analyse_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ld-analyse_autogen
.PHONY : ld-analyse_autogen

# fast build rule for target.
ld-analyse_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tools/ld-analyse/CMakeFiles/ld-analyse_autogen.dir/build.make tools/ld-analyse/CMakeFiles/ld-analyse_autogen.dir/build
.PHONY : ld-analyse_autogen/fast

ld-ldf-reader.o: ld-ldf-reader.c.o
.PHONY : ld-ldf-reader.o

# target to build an object file
ld-ldf-reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader.c.o
.PHONY : ld-ldf-reader.c.o

ld-ldf-reader.i: ld-ldf-reader.c.i
.PHONY : ld-ldf-reader.i

# target to preprocess a source file
ld-ldf-reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader.c.i
.PHONY : ld-ldf-reader.c.i

ld-ldf-reader.s: ld-ldf-reader.c.s
.PHONY : ld-ldf-reader.s

# target to generate assembly for a file
ld-ldf-reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader.c.s
.PHONY : ld-ldf-reader.c.s

ld-ldf-reader_autogen/mocs_compilation.o: ld-ldf-reader_autogen/mocs_compilation.cpp.o
.PHONY : ld-ldf-reader_autogen/mocs_compilation.o

# target to build an object file
ld-ldf-reader_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader_autogen/mocs_compilation.cpp.o
.PHONY : ld-ldf-reader_autogen/mocs_compilation.cpp.o

ld-ldf-reader_autogen/mocs_compilation.i: ld-ldf-reader_autogen/mocs_compilation.cpp.i
.PHONY : ld-ldf-reader_autogen/mocs_compilation.i

# target to preprocess a source file
ld-ldf-reader_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader_autogen/mocs_compilation.cpp.i
.PHONY : ld-ldf-reader_autogen/mocs_compilation.cpp.i

ld-ldf-reader_autogen/mocs_compilation.s: ld-ldf-reader_autogen/mocs_compilation.cpp.s
.PHONY : ld-ldf-reader_autogen/mocs_compilation.s

# target to generate assembly for a file
ld-ldf-reader_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ld-ldf-reader.dir/build.make CMakeFiles/ld-ldf-reader.dir/ld-ldf-reader_autogen/mocs_compilation.cpp.s
.PHONY : ld-ldf-reader_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ld-analyse_autogen"
	@echo "... ld-chroma-decoder_autogen"
	@echo "... ld-chroma-encoder_autogen"
	@echo "... ld-chroma-lib_autogen"
	@echo "... ld-disc-stacker_autogen"
	@echo "... ld-discmap_autogen"
	@echo "... ld-dropout-correct_autogen"
	@echo "... ld-export-metadata_autogen"
	@echo "... ld-ldf-reader_autogen"
	@echo "... ld-lds-converter_autogen"
	@echo "... ld-library_autogen"
	@echo "... ld-process-efm_autogen"
	@echo "... ld-process-vbi_autogen"
	@echo "... ld-process-vits_autogen"
	@echo "... target"
	@echo "... ld-analyse"
	@echo "... ld-chroma-decoder"
	@echo "... ld-chroma-encoder"
	@echo "... ld-chroma-lib"
	@echo "... ld-disc-stacker"
	@echo "... ld-discmap"
	@echo "... ld-dropout-correct"
	@echo "... ld-export-metadata"
	@echo "... ld-ldf-reader"
	@echo "... ld-lds-converter"
	@echo "... ld-library"
	@echo "... ld-process-efm"
	@echo "... ld-process-vbi"
	@echo "... ld-process-vits"
	@echo "... ld-ldf-reader.o"
	@echo "... ld-ldf-reader.i"
	@echo "... ld-ldf-reader.s"
	@echo "... ld-ldf-reader_autogen/mocs_compilation.o"
	@echo "... ld-ldf-reader_autogen/mocs_compilation.i"
	@echo "... ld-ldf-reader_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

