# Makefile for the Software Decode of Laserdiscs project

# Note: Targets do not include auto-generated .h files, which means
#       that make clean will not remove them.
TARGETS=cx tbc-pal tbc-pal32 tbc-ntsc tbc-ntsc40 tbc-ntsc44 ntsc4 comb-ntsc comb-pal ddpack ddunpack #tbc

CFLAGS=-g -O2 -fno-omit-frame-pointer -march=native
OPENCV_LIBS=-lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_video

# Define the directory for the TBC Qt app (relative to this makefile)
TBCAPP=./app/tbc/

all: $(TARGETS)

clean:
	rm -f $(TARGETS)
	$(MAKE) -C $(TBCAPP) clean

ddpack: ddpack.c
	gcc -std=c99 -O2 -o ddpack ddpack.c

ddunpack: ddunpack.c
	gcc -std=c99 -O2 -o ddunpack ddunpack.c

cx: cx-expander.cxx deemp.h
	clang++ -std=c++11  -Wall $(CFLAGS) -o cx cx-expander.cxx

deemp.h: filtermaker.py
	python3 filtermaker.py > deemp.h

ntsc4: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -Wall -g -DFSC4 -o ntsc4 tbc-ntsc.cxx

ntsc10: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -Wall $(CFLAGS) -DFSC10 -o ntsc10 tbc-ntsc.cxx

tbc-pal: tbc-pal.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -o tbc-pal tbc-pal.cxx

tbc-pal32: tbc-pal.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -DC32MHZ -o tbc-pal32 tbc-pal.cxx

tbc-ntsc: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -o tbc-ntsc tbc-ntsc.cxx

tbc-ntsc32: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -DC32MHZ -o tbc-ntsc32 tbc-ntsc.cxx

tbc-ntsc40: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -DC40MHZ -o tbc-ntsc40 tbc-ntsc.cxx

tbc-ntsc44: tbc-ntsc.cxx ld-decoder.h deemp.h
	clang++ -std=c++11  -g -Wall $(CFLAGS) -DC44MHZ -o tbc-ntsc44 tbc-ntsc.cxx

tbc-ntsc44g: tbc-ntsc.cxx ld-decoder.h deemp.h
	g++ -std=c++11  -g -Wall $(CFLAGS) -DC44MHZ -o tbc-ntsc44 tbc-ntsc.cxx
# New Qt5 based TBC - Calls the makefile in the application's
# directory (which is generated by qmake)
.PHONY: tbc

tbc:
	@$(MAKE) -C $(TBCAPP) all;

ntsc: tbc-ntsc

comb-ntsc: comb-ntsc.cxx deemp.h
	clang++ -lfann -std=c++11  -Wall $(CFLAGS) $(OPENCV_LIBS) -o comb-ntsc comb-ntsc.cxx
	cp comb-ntsc comb

comb-ntsc-eigen: comb-ntsc-eigen.cxx deemp.h
	clang++ -Ieigen -lfann -std=c++11  -Wall $(CFLAGS) $(OPENCV_LIBS) -o comb-ntsc-eigen comb-ntsc-eigen.cxx
#	cp comb-ntsc-euler comb

comb-pal: comb-pal.cxx deemp.h
	clang++ -lfann -std=c++11  -Wall $(CFLAGS) $(OPENCV_LIBS) -o comb-pal comb-pal.cxx

comb-paln: comb-paln.cxx deemp.h
	clang++ -lfann -std=c++11  -Wall $(CFLAGS) $(OPENCV_LIBS) -o comb-paln comb-paln.cxx

comb: comb-ntsc

test:
	./ldd snw.raw | ./ntsc - | ./comb - > snw.rgb
	convert -size 1488x480 -depth 8 rgb:snw.rgb -resize 640x480\! snw.png

