# known to work with 22.04, other versions may have incompatibilities
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get -y -qq install apt-utils sudo && \
    apt-get -y -qq install locales && locale-gen en_US.UTF-8;

RUN apt -y upgrade

# libqwt-qt5-dev
# python3-matplotlib
RUN apt -y install --no-install-recommends make cmake python3-numpy python3-scipy git qtbase5-dev libfftw3-dev python3-pandas python3-numba libavformat-dev libavcodec-dev libavutil-dev ffmpeg openssl pv cython3 pkg-config python3-setuptools libqt5core5a ca-certificates

# clone and build the latest master
RUN git clone --depth 2 https://github.com/oyvindln/vhs-decode.git

RUN cd vhs-decode && mkdir build2 && cd build2 && cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DUSE_QWT=OFF && make && make install
WORKDIR /vhs-decode
RUN python3 setup.py install && rm -r build2

# remove build stuff
RUN apt -y remove qtbase5-dev make cmake pkg-config git --autoremove

# clean up intermediate files to make docker image smaller
RUN apt-get clean

##### TODO upstream : only look for find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Gui Widgets) if gui is used
