from math import pi

AUDIO_MODE_STEREO = "s"
AUDIO_MODE_STEREO_MS = "ms"
AUDIO_MODE_DUAL_MONO = "d"
AUDIO_MODE_DUAL_MONO_MS = "dms"
AUDIO_MODE_MONO_L = "l"
AUDIO_MODE_MONO_R = "r"
AUDIO_MODE_MONO_SUM = "sum"

UI_STEREO = "Stereo (L, R)"
UI_STEREO_MS = "Stereo (L+R, L-R)"
UI_DUAL_MONO = "Dual Mono (L) (R)"
UI_DUAL_MONO_MS = "Dual Mono (L+R) (L-R)"
UI_MONO_L = "Mono (L)"
UI_MONO_R = "Mono (R)"
UI_MONO_SUM = "Mono Sum (L+R)"

DEFAULT_VHS_AUDIO_MODE = AUDIO_MODE_STEREO
DEFAULT_8MM_AUDIO_MODE = AUDIO_MODE_STEREO_MS

audio_mode_to_ui = {
    AUDIO_MODE_STEREO: UI_STEREO,
    AUDIO_MODE_STEREO_MS: UI_STEREO_MS,
    AUDIO_MODE_DUAL_MONO: UI_DUAL_MONO,
    AUDIO_MODE_DUAL_MONO_MS: UI_DUAL_MONO_MS,
    AUDIO_MODE_MONO_L: UI_MONO_L,
    AUDIO_MODE_MONO_R: UI_MONO_R,
    AUDIO_MODE_MONO_SUM: UI_MONO_SUM,
}

ui_to_audio_mode = {
    UI_STEREO: AUDIO_MODE_STEREO,
    UI_STEREO_MS: AUDIO_MODE_STEREO_MS,
    UI_DUAL_MONO: AUDIO_MODE_DUAL_MONO,
    UI_DUAL_MONO_MS: AUDIO_MODE_DUAL_MONO_MS,
    UI_MONO_L: AUDIO_MODE_MONO_L,
    UI_MONO_R: AUDIO_MODE_MONO_R,
    UI_MONO_SUM: AUDIO_MODE_MONO_SUM,
}

DOC_MODE_FULL = "full"
DOC_MODE_MUTE = "mute"
DOC_MODE_DISABLED = "off"

UI_DOC_MODE_FULL = "Full"
UI_DOC_MODE_MUTE = "Muting Only"
UI_DOC_MODE_DISABLED = "Off"

DEFAULT_DOC_MODE = DOC_MODE_FULL

doc_mode_to_ui = {
    DOC_MODE_FULL: UI_DOC_MODE_FULL,
    DOC_MODE_MUTE: UI_DOC_MODE_MUTE,
    DOC_MODE_DISABLED: UI_DOC_MODE_DISABLED,
}

ui_to_doc_mode = {
    UI_DOC_MODE_FULL: DOC_MODE_FULL,
    UI_DOC_MODE_MUTE: DOC_MODE_MUTE,
    UI_DOC_MODE_DISABLED: DOC_MODE_DISABLED,
}

DEFAULT_VHS_EXPANDER_GAIN = 30
DEFAULT_VHS_EXPANDER_RATIO = 2
DEFAULT_VHS_EXPANDER_ATTACK_TAU = 6.5e-3
DEFAULT_VHS_EXPANDER_HOLD_TAU = 0
DEFAULT_VHS_EXPANDER_RELEASE_TAU = 70e-3

DEFAULT_VHS_DEEMPHASIS_TAU_1 = 56e-6
DEFAULT_VHS_DEEMPHASIS_TAU_2 = 20e-6
DEFAULT_VHS_EXPANDER_WEIGHTING_TAU_1 = 240e-6
DEFAULT_VHS_EXPANDER_WEIGHTING_TAU_2 = 24e-6
DEFAULT_VHS_EXPANDER_WEIGHTING_LOW_PASS = 20000
DEFAULT_VHS_EXPANDER_WEIGHTING_LOW_PASS_TRANSITION = 100000
DEFAULT_VHS_NR_DEEMPHASIS_TAU_1 = 240e-6
DEFAULT_VHS_NR_DEEMPHASIS_TAU_2 = 56e-6

DEFAULT_8MM_EXPANDER_GAIN = 6
DEFAULT_8MM_EXPANDER_RATIO = 2
DEFAULT_8MM_EXPANDER_ATTACK_TAU = 3e-3
DEFAULT_8MM_EXPANDER_HOLD_TAU = 15e-3
DEFAULT_8MM_EXPANDER_RELEASE_TAU = 40e-3
DEFAULT_8MM_NR_DEEMPHASIS_TAU_1 = 75e-6
DEFAULT_8MM_NR_DEEMPHASIS_TAU_2 = 19e-6
DEFAULT_8MM_DEEMPHASIS_TAU_1 = 75e-6
DEFAULT_8MM_DEEMPHASIS_TAU_2 = 27e-6
DEFAULT_8MM_EXPANDER_WEIGHTING_TAU_1 = 75e-6
DEFAULT_8MM_EXPANDER_WEIGHTING_TAU_2 = 27e-6
DEFAULT_8MM_EXPANDER_WEIGHTING_LOW_PASS = 20000
DEFAULT_8MM_EXPANDER_WEIGHTING_LOW_PASS_TRANSITION = 100000

DEFAULT_SPECTRAL_NR_AMOUNT = 0.4
DEFAULT_RESAMPLER_QUALITY = "high"
DEFAULT_FINAL_AUDIO_RATE = 48000

DEMOD_QUADRATURE = "quadrature"
DEMOD_HILBERT = "hilbert"
DEFAULT_DEMOD = DEMOD_QUADRATURE


def tau_as_freq(tau):
    return 1 / (2 * pi * tau)
